site_name: mkquartodocs
site_url: https://jspaezp.github.io/mkquartodocs/
site_description: mkquartodocs extension
site_author: J. Sebastian Paez

repo_url: https://github.com/jspaezp/mkquartodocs

theme:
  name: material

nav:
  - Home: README.md

plugins:
  - search
  - mkdocstrings
  - mkquartodocs
