[tool.poetry]
name = "mkquartodocs"
version = "0.1.0"
description = ""
authors = ["J. Sebastian Paez <jspaezp@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "mkquartodocs"}]

[tool.poetry.dependencies]
python = ">3.8,<3.11"
mkdocs = "^1.3.1"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
isort = "^5.10.1"
pylint = "^2.15.2"
pydocstringformatter = "^0.7.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.plugins."mkdocs.plugins"]
"mkquartodocs" = "mkquartodocs.plugin:MkDocstringPlugin"
# Equivalent to:
# entry_points={
#     'mkdocs.plugins': [
#         'pluginname = path.to.some_plugin:SomePluginClass',
#     ]
# }
