
name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black
        uses: psf/black@stable
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
